version: '3.9'
services:
  local-apache:
    environment:
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - PHP_IDE_CONFIG=serverName=local.docker
      - SSH_AUTH_SOCK=/ssh-agent


  local-postgresql:
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: --auth-host=md5
      POSTGRES_HOST_AUTH_METHOD: md5

  local-mysql:
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
