version: '3.9'
services:
  dev-apache:
    ports:
      - "80:80"
      - "83:83"
      - "443:443"
    expose:
      - "9000"
      - "9003"
    networks:
      webmgr_net:

  dev-memcached:
    ports:
     - "11211:11211"
    networks:
      webmgr_net:

  dev-postgresql:
    ports:
      - "5445:5432"
    networks:
      webmgr_net:

  dev-redis:
    ports:
      - "6379:6379"
    networks:
      webmgr_net:

  dev-image-resizer:
    ports:
      - "8004:80"
    networks:
      webmgr_net:

networks:
  webmgr_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
