version: '3.9'
services:
  dev-apache:
    volumes:
      # - ${HOME}/.composer:/.composer
      - ./apache/.bashrc:/home/docker/.bashrc
      - ./apache/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./apache/docker.virtual_host.conf:/etc/httpd/conf.d/docker.virtual_host.conf
      - ./apache/php.ini:/etc/php.ini
      - ./apache/www.conf:/etc/php-fpm.d/www.conf
      - ./apache/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./apache/sites-enabled/000-default.conf:/etc/httpd/conf.d/000-default.conf
      - ./config/.env:/var/www/html/api/.env
      - ./config/.env:/var/www/.env
      - ./www/logs:/var/log/httpd
      - ./www/html:/var/www/html
      - ./www/media:/var/media
      - ./apache/motd:/etc/motd
      # - ./apache/etc/apache2/conf/pagespeed_localhost_ssl.conf:/etc/httpd/conf.d/pagespeed_localhost_ssl.conf
      - ${SSH_AUTH_SOCK}:/ssh-agent


