version: '3.9'
services:
  dev-apache:
    ports:
      - "80:80"
      - "83:83"
      - "443:443"
    expose:
      - "9000"
      - "9003"
    networks:
      webmgr_net:



networks:
  webmgr_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.55.0/24
