version: '3.9'
services:
  dev-apache:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "dev.slogin.smbportal.com:127.0.0.1"
      - "cimg.vm:127.0.0.1"
      - "api.webmgr.vm:127.0.0.1"
      - "api.webmgr.local:127.0.0.1"
      - "local-development.webmgr.com:127.0.0.1"
      - "local-webmgr-mastersite.com:127.0.0.1"
      - "my.local-brimhallwebsite.com:127.0.0.1"
      - "my.local-chiromatrix.com:127.0.0.1"
      - "my.local-dentrix:127.0.0.1"
      - "my.local-imatrix.com:127.0.0.1"
      - "my.local-martindalenolo.com:127.0.0.1"
      - "my.local-officite.com:127.0.0.1"
      - "my.local-onlinechiro.com:127.0.0.1"
      - "my.local-onlinepodiatrysites.com:127.0.0.1"
      - "my.local-theonlinepractice.com:127.0.0.1"
      - "my.local-vetmatrix.com:127.0.0.1"
      - "dev-webmgr-mastersite.internetbrands.com:10.161.134.148"
      - "stg-webmgr-mastersite.internetbrands.com:10.161.149.96"
      - "smb.internetbrands.com:10.161.134.196"
      - "git.internetbrands.com:10.16.82.40"
      - "stg-leads.internetbrands.com:10.161.134.173"
      - "ci.slogin.smb.internetbrands.com:10.161.134.196"
      - "apps.qa-officite.com:10.161.134.186"
      - "stg-smb-dns.internetbrands.com:10.161.134.195"
      - "ci.apps.smb.internetbrands.com:10.161.134.196"
      - "stg-smb-jenkins1.internetbrands.com:10.161.134.196"
      - "dev-leads.internetbrands.com:10.161.134.43"
      - "ci_legal.slogin.smb.internetbrands.com:10.161.134.196"
      - "ci_imatrix.slogin.smb.internetbrands.com:10.161.134.196"
      - "login.qa-officite.com:10.161.134.186"
      - "login.qa-nolo.com:10.161.134.186"
      - "apps.qa-modmedweb.com:10.161.134.186"