version: '3.9'
services:
  dev-apache:
    volumes:
      # - ${HOME}/.composer:/.composer
      - ./apache/.bashrc:/home/docker/.bashrc
      - ./apache/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./apache/docker.virtual_host.conf:/etc/httpd/conf.d/docker.virtual_host.conf
      - ./apache/php.ini:/etc/php.ini
      - ./apache/www.conf:/etc/php-fpm.d/www.conf
      - ./apache/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./www/logs:/var/log/httpd
      - ./www/html:/var/www/html
      - ./www/media:/var/media
      - ./apache/motd:/etc/motd
      # - ./apache/etc/apache2/conf/pagespeed_localhost_ssl.conf:/etc/httpd/conf.d/pagespeed_localhost_ssl.conf
      - ${SSH_AUTH_SOCK}:/ssh-agent

  dev-postgresql:
    volumes:
      - ./postgresql/psql-entrypoint-scripts:/docker-entrypoint-initdb.d:rw
      - webmgr_volume_db14:/var/lib/postgresql/data
      - ./postgresql/data:/data

  dev-image-resizer:
    volumes:
      - ./image-resizer:/var/www/sites/image-resizer
      - ./www/media:/var/content/ib-images/smb/webmgr

volumes:
  webmgr_volume_db14:
